### ISSUE TITLE
File signing

### ISSUE THREAD

**Issue by HACKERALERT** [Picocrypt/Picocrypt#21]
This is far from concrete or important, but worth putting here as a potential major addition.

PGP is hard (for the average user). It took me a while to learn how to use Kleopatra to sign previous Picocrypt releases. Given Pico's simplicity, it would be awesome if we could create a simple and footgun-proof file signing feature. It could be in a separate tab called Signing.

Low priority.

**Comment by hakavlad** [comment]
>PGP is hard (for the average user)

Minisign already exists.

**Comment by HACKERALERT** [comment]
Not everyone knows how to use CLI. Although minisign can be a good starting point, we can just use it and implement a GUI component for it in Picocrypt and not have to reinvent anything.

**Comment by JohnPlanetary** [comment]
I agree, it is a nice addition, not essential since is not the main focus of the application but very interesting.

The only signing scheme that I see used all the time by common people is PDF signature with digital certificates and timestamps.
The only other thing where signatures are common is in executable applications.

I would suggest supporting common certificates from National ID's secure chips, also PFX/ P12 files, and in the Microsoft Windows also support certificates that are in the Windows Certificate Store (one can access it using: certmgr.msc from the Run Prompt "Windows key" + "R". Maybe also include some self made digital certificate generator. Using for example: RSA 4096 bit SHA256; RSA 8192 bit SHA384 ; or RSA 16384 bit SHA512. 
I would skip Elliptic curves since even the common available ("supreme") NIST P-521 should provide less security then some RSA-3072 bit SHA256 private/ public key... yes, they were supposed to be at the 16384 bit RSA level, but I've seen at least a source saying that if quantum computing becomes reality to the point of being able to really crack the keys in practice NIST P-521 is equivalent to less then RSA 3072 bit.
You can have support for elliptic curves, just not promote them in the built in public/ private key generator.

The integration of the common used PKI is to make it more usable by common people. Not saying everyone knows how to use PKI, but since so many people need to use it (at least lawyers and other people in the legal area, and even common people to sign digital contracts and similar documents becoming more and more common) these makes it more useful.

The hash for file integrity should probably be SHA512 since that should provide the best protection in the long term.

PGP, OpenPGP, Minisign, and Academic Signature, are by no stretch of imagination as much popular or used as PKI in the real world... with PKI the person can have some level of trust assurance... key management in the other ones (PGP, OpenPGP, Minisign, and Academic Signature) is a nightmare and only very technical people really use it, and probably rarely.
If privacy is needed one can make its own PKI structure (using XCA - https://github.com/chris2511/xca/releases ) or use the built in key generator of the Picocrypt (if you decide to include one).

Ideally the program would allow it to be integrated into the Picocrypt file, allowing the inspection before opening the encrypted file, or if deniability is used it would be included inside the encrypted file allowing to inspect the certificate during the decryption phase to confirm everything inside is ok and is from the expected source... these would require some option to select "Digital Signature required to allow full decipher" possibly with extra options like: "I will inspect the digital certificate manually", "Only allow from the authorized approved list", and if both selected it would first check if it is in the approved list and only then display the digital certificate for inspection... these can be used to reduce exposure to vulnerabilities and attacks.
If "Digital Signature required to allow full decipher" is not selected the program would still display the certificate(s) information if any is available otherwise would just decrypt as usually.

Sometimes having the timestamp may be useful, example: to indicate the exact time and date of the file can help to identify if someone has tampered the file(s) inside, or to help other person to know if it is the correct file(s) since people can talk personally and tell the other the exact time and date of the file and who is the trusted third party.
For these I suggest RFC 3161 and RFC 5816 support.
Maybe even include some common used TimeStamp services like:
- http://timestamp.digicert.com (SHA512)
- http://time.certum.pl (SHA512)
- https://timestamp.sectigo.com (SHA512)
- http://sha256timestamp.ws.symantec.com/sha256/timestamp (SHA512)
and allow the user to add other ones that the user can always use or just sometimes. Support username & password, or certificate based authentication to the timestamp server. Also support "nonce" (I think it is used to prevent replay attacks, some providers require these). Also support "TSA policy ID" that some providers require users to enter. Allow to select between at least "SHA512", "SHA384" and "SHA256" since different TimeStamp services require/ support different hashing algorithms.

If a certificate chain is identify it should include OCSP and CRL offline data to allow the file to stay valid even after the timestamp certificate expires. CRL files can be very big, so users should be aware of that... but many times CRL is the only thing available and a good operator can keep it small if they manage things properly. For these reason it may be a good idea to allow to only include OCSP if supported since CRL may make the file too big, but will require the receiving end to download there if it wants to verify it the certificate is valid and wasn't revoked (and maybe allow the receiving end to integrate into the file since it may make sense for the end point to be able to keep the information, but not include it in the initial hosting/ delivery to reduce the file size/ cost/ time to delivery over the network.

Allow to use digital certificate to identify and timestamp, or just digital certificate to identify, or just timestamp... since every situation is different and one may just want to timestamp or just identify himself/ herself or do both. Flexibility is nice to have.

These would mean that it should be displayed in the Picocrypt interface the available information in its own tab (previous verification) and when the operation is being done (on the fly verification).

I think it would be also nice to be able to do the same to normal files outside of Picocrypt encrypted file format, in that case it could be either a totally outside file to the normal file (ex.: mydocument.docx and mydocument.docx.picosign) or some sort of zip file with the digital signature and/ or timestamp similar to the ".asic" format, that is basically a zip file with everything inside (ex.: mydocument_docx.zippicosign).

Skip display digital certificate and/ or timestamp information should be available, since not everyone will want that.
Have some option to "not allow"/ "require permission" to fetch any OCSP/ CRL information update should also be available.
Some option to not download the root and or intermediate certificates should also be available.
OCSP/ CRL/ Root certificate/ Intermediate certificates can be used by some attacker (malicious or not) to flag the location of the user since the program will send a request and there is nothing to prevent to have a personalized URL just for that person. Other uses is for example to allow the attacker to know the file was open/ seen since they should only be getting a signal in that specific address if someone has access to the file and knows where to go look. One can use privacy proxy's, onion network or VPN to try to reduce the chances of revealing the location but would at least give the signal of access to the file and that is a privacy concern.
These said the Picocrypt should offer the option to get all that updated information: OCSP/ CRL/ Root certificate/ Intermediate certificates, since it may be useful for the user and in some cases may be very useful, specially if it isn't included in the original file.

Common used digital certificates and timestamps root and intermediate certificates should be included, and allow the user to add/ remove/ reset the list.

In the end of the day making secure digital signing correctly is probably too much work, but is something new in the "business" since currently the only way to sign normal files would be to create some executable (.exe) with for example 7-zip and then use some file signer like "SignToolGUI" ( https://github.com/GlitchedPolygons/SigntoolGUI ) to sign them by signing the executable that contains the files (advantage being that the executable can self-extract, but if some Microsoft Windows user sends to some macOS or Linux friend it won't be able to open) . Of course one can use the XolidoSign to create external signature, but that wouldn't be something included in the file himself and would require from the receiving end yet another tool to read that external signature file to compare with the file and see if it matches... and if the user doesn't have Microsoft Windows then XolidoSign to read the information can't be used... XolidoSign probably needs administration level access in Microsoft Windows.

I guess Picocrypt with digital signing can be a huge but interesting addition, depending on the implementation way.

The PKI should make it easier to use and trust, but you can go your own way and force PGP/ Minisign style signatures, that would work but probably most people, me included, wouldn't use... and even PKI I'm guessing won't be massively used... except the secure timestamp since wouldn't require more than select that for it to "just work"... the digital certificate will be the hard part for most people (me included) if the user interface isn't intuitive or if it gives errors that needs expert changes for it to work.

I'm not a expert in these, neither I'm a coder, but I hope these demonstrates my interest in these functionality and gives some ideas to explore to eventually integrate signing into the PicoCrypt application.

I was hopping for years for some popular compression tool to include these, but never happen.

**Comment by HACKERALERT** [comment]
> I'm not an expert in these

And then drops a massive comment of info : 😊 

Yes, there are many ways to do it. And to be honest, I'm not sure if it's even worth the complexity. I was initially thinking something super simple like a very basic nacl box like backend and simple frontend that used kyber768-x25519. Would be sufficiently secure and reasonably simple. But I may also be butchering things with my limited knowledge of public key crypto

**Comment by JohnPlanetary** [comment]
Not expert in the sense of understanding all the math involved, and being able to code anything related.

But I obviously like the subject enough to have some understanding of it.

The PKI makes it easy for real world identification.

Self made simple kyber768-x25519 key would also work, but would be (close to) impossible to track back into someone real since one would need to get that information from the person itself or from the company/ organization, and even then who knows if it is real, it is the same problem as in PGP, OpenPGP, Minisign, and Academic Signature, since no third party is involved to provide some level of assurance over the provided information.

That said if you decide to go the easy way and just have kyber768-x25519 at least make it easy for the user to comment on the key to identify the person/ web site/ e-mail or whatever else makes sense to improve the usefulness of it for ID purposes.

I still think secure third party timestamps (RFC 3161 and RFC 5816) would make the application more useful and that is more likely to be used since it would "just work" without the need for key generation and management by the user, and would provide at least some authentication level of the data if people keep a record of it, since faking some third party timestamp server, specially if from a bigger company would be much harder then at least fake the local computer time and date.

**Comment by HACKERALERT** [comment]
No plans to work on this necessarily, but if you have any particular formats or Go libraries that you think might be suitable, feel free to put here in case someone else wants to do some experimental work on it.

**Comment by HACKERALERT** [comment]
Actually this seems really easy to do with https://pkg.go.dev/crypto/ed25519 (standard crypto library). Might be a separate CLI tool along the lines of:
`sign generate`: generates your public + private key
`sign whoami`: returns your public key
`sign trust <key>`: trust someone else's public key
`sign verify <file>`: verify <file>.sig by testing all trusted public keys

Even simpler than minisign :)

**Comment by JohnPlanetary** [comment]
Not sure if is appropriated but: https://pkg.go.dev/github.com/notaryproject/tspclient-go seems to provide timestamp functions according to RFC 3161 and RFC 5816.

**Comment by HACKERALERT** [comment]
Keeping Picocrypt "pico"... I think this is not necessary.
