### ISSUE TITLE
[MAJOR v1.42 Bug] Decrypts with any password (even a wrong one)

### ISSUE THREAD

**Issue by Jack5005** [Picocrypt/Picocrypt#52]
OS: Windows 11 Home
Picocrypt GUI ver: 1.42

I did 2 separate encrypts. One reported here and the other reported in this [linked spot](https://github.com/Picocrypt/CLI/issues/11). 

This particular encryption was a folder pico encrypted (paranoid disabled). It made it .zip.pcv (not compressed). I encrypted it with a complicated password. Then I tried to decrypt it using the password "123" and it started the decryption process! ...

**Comment by Retengart** [comment]
@Jack5005, I tried to reproduce your issue on my Windows 10 system. I must admit that it is not possible to decrypt files using an incorrect password in order to obtain the original files. I suspect that you may have enabled the "Force decrypt" option, which forcibly stores the decryption results (even if the password is incorrect). However, please note that these results will be in the form of binary GARBAGE that has no connection to your original data.
![image](https://github.com/user-attachments/assets/c2f635f6-3a20-4366-bbb4-c9a66d9cb59c)

**Comment by HACKERALERT** [comment]
Yes, please read the documentation before assuming someone is broken. Force decrypt assumes you know what you are doing and will attempt to decrypt even if the password is wrong.

**Comment by Jack5005** [comment]
> Yes, please read the documentation before assuming something is broken. Force decrypt assumes you know what you are doing and will attempt to decrypt even if the password is wrong.

Oh ok, my bad. I thought I had read all of the docs that was relevant to what I was looking for but apparently not. Will take a second look!
