### ISSUE TITLE
Declare checksums of Picocrypt executables

### ISSUE THREAD

**Issue by d-e-n-n-i-s-t** [Picocrypt/Picocrypt#72]
I think it would be a nice addition to declare the checksums of the files when releasing a new version. It just adds a little bit of security to check against corrupt/malicious binaries

**Comment by HACKERALERT** [comment]
Worth mentioning for the sake of transparency that I can technically edit a release after GitHub Actions releases it, so I can (if I wanted to) upload a bunch of modified binaries and it'll still look like a GitHub Actions release. I won't do that obviously, and I'm saying this not to scare anyone but to state something that's not obvious (I didn't know about this either). If you're incredibly paranoid, you can build from source. But otherwise, I let GitHub Actions do the release and I won't touch any release files so it's safe.

**Comment by d-e-n-n-i-s-t** [comment]
@HACKERALERT Im not really paranoid about getting the files here, I just think its good practice to define the checksums of the official files somewhere. As said in my first message, it's also practical  for checking against file corruption (with programs like this, the integrity of the executable is even more important than with other programs)

**Comment by HACKERALERT** [comment]
If an executable corrupts, it most likely won't even run so I wouldn't worry about it too much. GitHub is a big platform, I think they have enough reliability to not have files corrupting :)

**Comment by d-e-n-n-i-s-t** [comment]
Thanks for including the checksums in the latest release!
